export {default as vacancySlice} from './model/vacancyPageAddSlice'
export {default as vacancyPageParseSlice} from './model/vacancyPageParseSlice'
export {fetchVacancyData} from './model/vacancyPageParseThunk'
export {vacancyPageAddThunk} from './model/vacancyPageAddThunk'
export {getVacancyJobs} from './model/selectors/selectors'
